const homepagedata = [
  {
    headLabel: "HTML",
    headSubHeading: "The Language For Building Web Pages",
    button: "Learn HTML",
    buttonLink: "hey",
    buttonReferenceLink: "hey2",
    buttonReference: "HTML Reference",
    titleExample: "HTML EXAMPLE",
    codeDescription: "<HTML> \n <Head> \n </Head>\n <Body>\n   <h1>hey there! </h1> \n </Body> \n</HTML> ",
    codeName: 'language-markup',
    tryItButton: "try it Yourself",
    color: "#282A35",
    tryItButtonLink:
      "https://www.w3schools.com/html/tryit.asp?filename=tryhtml_default",
  },
  {
    headLabel: "CSS",
    headSubHeading: "The Language For Styling Web Pages",
    button: "Learn CSS",
    buttonLink: "hey",
    buttonReferenceLink: "hey2",
    buttonReference: "CSS Reference",
    codeDescription: '#class { \n background-color: red; }',
    codeName: 'language-css',
    titleExample: "CSS EXAMPLE",
    tryItButton: "try it Yourself",
    tryItButtonLink:
      "https://www.w3schools.com/css/tryit.asp?filename=trycss_default",
    color: "#282A15",
  },
  {
    headLabel: "JAVASCRIPT",
    headSubHeading: "The Language For Programming Web Pages",
    button: "Learn JavaScript",
    buttonLink: "hey",
    buttonReferenceLink: "hey2",
    codeName: 'language-js',
    codeDescription: 'function myFunction() { \n var x = document.getElementById("demo"); \n x.style.fontSize = "25px"; \n x.style.color = "red"; \n}',
    buttonReference: "JavaScript Reference",
    titleExample: "JavaScript EXAMPLE",
    tryItButton: "try it Yourself",
    tryItButtonLink:
      "https://www.w3schools.com/js/tryit.asp?filename=tryjs_default",
    color: "#281A35",
  },
  {
    headLabel: "PYTHON",
    headSubHeading: "The Language For Programming Web Pages",
    button: "Learn Python",
    buttonLink: "hey",
    buttonReferenceLink: "hey2",
    buttonReference: "Python Reference",
    titleExample: "Python EXAMPLE",
    tryItButton: "try it Yourself",
    tryItButtonLink:
      "https://www.w3schools.com/python/trypython.asp?filename=demo_indentation",
    color: "#272A35",
  },
  {
    headLabel: "SQL",
    headSubHeading: "The Language For Accessing Database",
    button: "Learn SQL",
    buttonLink: "hey",
    buttonReferenceLink: "hey2",
    buttonReference: "SQL Reference",
    titleExample: "SQL EXAMPLE",
    tryItButton: "try it Yourself",
    codeDescription: "SELECT * FROM Customers \n WHERE Country='Mexico';",
    codeName: 'language-python',
    tryItButtonLink:
      "https://www.w3schools.com/sql/trysql.asp?filename=trysql_select_where",
    color: "#382A35",
  },
];
export default homepagedata;
